name: Master-CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run Tests
        run: python3 src/tests.py
        env:
          DATABASE_URL: mock

      - name: Build Docker Image
        run: docker build -t flask-app .

      - name: Start Docker Container
        run: docker run -d --name flask-app-container flask-app

      - name: Get Container Logs
        run: docker logs flask-app-container